### ISSUE TITLE
Image / Buttons not compatible in Studio story configuration 

### ISSUE THREAD

**Issue by dabadiesimon** [theopenconversationkit/tock#966]
On tock Studio: When adding an image as answer in a story with buttons :

1. buttons don't appear anymore on the "Test" of Tock Studio
2. buttons are repeated x times (where x is the number of images added) in the Web Connector

1) has been replicated on current online version + version 20
2) has been experimented on version 20 (not tested on current online version)

Images are from online version
![image](https://user-images.githubusercontent.com/52737632/85050861-0c22b280-b197-11ea-8955-9e19559e08f1.png)
![image](https://user-images.githubusercontent.com/52737632/85050904-1a70ce80-b197-11ea-98ae-09c7a89b35d3.png)
![image](https://user-images.githubusercontent.com/52737632/85050997-396f6080-b197-11ea-9175-e2bda3e033a0.png)
![image](https://user-images.githubusercontent.com/52737632/85051030-455b2280-b197-11ea-9190-0b5e4745a3a5.png)

**Comment by vsct-jburet** [comment]
@dabadiesimon the bug in the test interface is fixed on the demo platform, but how can you have more than one image in the response of WebConnector ?

Please checks the demo and let me know if everything is ok now  ;)

**Comment by dabadiesimon** [comment]
@vsct-jburet 
- great the test interface is now displaying buttons properly, thanks !
- when adding several images, the buttons are repeated (bug is still active on the online demo) - see screenshot on the test interface and json response of the Web connector

![image](https://user-images.githubusercontent.com/52737632/85369707-ddf1f980-b52d-11ea-8465-adb1a6e5cae2.png)
![image](https://user-images.githubusercontent.com/52737632/85369750-f6621400-b52d-11ea-88e0-b7b72cac3c61.png)

{
  "responses": [
    {
      "type": "WebMessage",
      "text": "EPIs pour quelle méthode ?",
      "version": "1"
    },
    {
      "type": "WebMessage",
      "card": {
        "file": {
          "url": "https://demo-bot.tock.ai/f/dabadiesimonaf43ba43-c88c-4a15-972c-671d12df188e.png",
          "name": "man.png",
          "type": "image"
        },
        "buttons": [
          {
            "clazz": "postback_button",
            "title": "percage/gel hydrique",
            "type": "postback"
          },
          {
            "clazz": "postback_button",
            "title": "percage/humidification",
            "type": "postback"
          }
        ]
      },
      "version": "1"
    },
    {
      "type": "WebMessage",
      "text": "2e texte",
      "version": "1"
    },
    {
      "type": "WebMessage",
      "card": {
        "file": {
          "url": "https://demo-bot.tock.ai/f/dabadiesimonaa4d38f5-819c-488b-a356-c7346503a58c.png",
          "name": "Heka_Logo-01.png",
          "type": "image"
        },
        "buttons": [
          {
            "clazz": "postback_button",
            "title": "percage/gel hydrique",
            "type": "postback"
          },
          {
            "clazz": "postback_button",
            "title": "percage/humidification",
            "type": "postback"
          }
        ]
      },
      "version": "1"
    }
  ]
}

**Comment by vsct-jburet** [comment]
Will be fixed on the demo platform soon
